[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "tc"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = ["attrs"]
